// Assistant Hub (roadmap/assistant-hub/, WP1.7) — the mission sub-module public surface. The hub
// wiring (`index.ts`) and the routes barrel (`hub/routes.ts`) import from here.
export {
  AGENT_REPORT_PROJECTED_NOTE,
  buildAgentReportContractInstruction,
  HUB_AGENT_REPORT_FENCE,
  noteProjectedReport,
  parseAgentReportContract,
  type HubAgentReportParse,
} from "./agent-report-contract.js";
export {
  allocateChildBudget,
  buildMissionPlannerPrompt,
  buildPlannerServerCatalog,
  clampGrantsToCatalog,
  clampPlannedCredentials,
  clampPlanToBudgets,
  coerceTopology,
  createStructuredPlanner,
  estimateAgentCostUsd,
  estimatePlanCostUsd,
  MISSION_AGENT_TOKEN_ENVELOPE,
  normalizePlannedModels,
  notePlanPricingGaps,
  summarizeMissionTree,
  type HubMissionCaps,
  type HubPlanner,
  type HubPlannerInput,
  type HubPlannerServerCatalog,
  type HubPlannerServerCatalogEntry,
  type MissionTreeSummary,
} from "./planner.js";
export {
  formatModelRoster,
  HUB_MODEL_TIERS,
  isStructuredOutputModel,
  pickSynthesisModel,
  RESERVED_MODEL_TIERS,
  tierForModel,
  type HubModelRef,
  type HubModelTier,
  type HubRosterModel,
} from "./roster.js";
export {
  createSessionAgentRunner,
  createStructuredAgentRunner,
  HUB_AGENT_REPORT_EXTRACTION_MARKER,
  HubAgentReportContractError,
  HubMissionService,
  isTerminalMissionStatus,
  shouldAutoApprove,
  type HubAgentRunInput,
  type HubAgentRunner,
  type HubAgentRunResult,
  type HubMissionServiceConfig,
  type HubMissionServiceDeps,
  type HubResolvedCrew,
} from "./orchestrator.js";
export {
  composeCrewBrief,
  composeHandoffBrief,
  createStructuredJudge,
  crewRefToPlannedAgent,
  deterministicWinner,
  DROPPED_DEBATER_NOTE,
  hydratePlannedAgentFromRole,
  instantiateCrewPlan,
  pinForModel,
  roleToPlannedAgent,
  runTopology,
  type HubJudge,
  type HubJudgeAttempt,
  type HubJudgeInput,
  type HubJudgeResult,
  type TopologyContext,
  type TopologyOutcome,
  type TopologySlot,
} from "./topologies.js";
export {
  buildReportsDigest,
  createTextSynthesizer,
  mergeAgentCitations,
  synthesizeMission,
  type HubSynthesizer,
  type HubSynthesizerInput,
  type HubSynthesizerResult,
  type MergedCitations,
} from "./synthesis.js";
export {
  isMissionBoardTerminal,
  reconstructMission,
  reconstructMissionById,
  type MissionBoardAgent,
  type MissionBoardPhase,
  type MissionBoardState,
} from "./board.js";
export {
  registerHubMissionRoutes,
  type HubMissionChannels,
  type HubMissionRouteDeps,
} from "./routes.js";
export {
  agentToolSignatures,
  clampDebateRounds,
  composeDebateRoundBrief,
  DEBATE_ROUND_BRIEF_INTRO,
  DEBATE_ROUNDS_DEFAULT,
  DEBATE_ROUNDS_MAX,
  HUB_ROLE_PLACEHOLDER_MARKERS,
  plannedAgentLabel,
  plannedAgentNeedsConfiguration,
  renderReportText,
  summarizeBudgets,
  summarizeServerCapability,
} from "./shared.js";
