import {
  DIAGNOSTICS_ERROR_ENTRY_LIMIT,
  DIAGNOSTICS_ERROR_MAX_CHARS,
  type DiagnosticsBundle,
  type DiagnosticsEnvStatus,
  type DiagnosticsErrorSourceId,
} from "@mcp-token-footprint/shared";
import { escapeMarkdownTable, escapeText } from "../reports/reports.js";

// ── Diagnostics bundle → Markdown (planning/Roadmap/RM-18-platform/ WP 1.3) ─────────────────────
//
// The house pattern (`fleet-report.ts` + `fleet-report-markdown.ts`, `digest.ts` +
// `digest-markdown.ts`): a PURE function whose ONLY parameter is the already-composed payload. That
// signature is the guarantee the WP asks for — this renderer cannot reach the environment, the
// database or the app config, because it is not given them. JSON and Markdown are therefore the
// same document rendered twice, and a sentinel sweep over one sweeps the other's inputs too.
//
// `apps/api/test/diagnostics.test.ts` pins that by walking THIS file's source for the names of
// those three doors, so the paragraph above cannot quietly stop being true. Which is why it does
// not spell any of them out literally: a source pin that its own prose trips is a pin nobody keeps.
//
// Sections mirror the payload's five groups in the order a reader wants them: what this install IS,
// how it is configured, what its database looks like, what has gone wrong, and what is switched on.

/** Digit grouping without `toLocaleString` — locale-dependent output would not be byte-stable. */
function count(value: number): string {
  const digits = Math.abs(Math.round(value)).toString();
  let grouped = "";
  for (let i = 0; i < digits.length; i += 1) {
    if (i > 0 && (digits.length - i) % 3 === 0) grouped += ",";
    grouped += digits[i];
  }
  return value < 0 ? `-${grouped}` : grouped;
}

function bytes(value: number | null): string {
  if (value === null) return "not measured";
  if (value < 1024) return `${count(value)} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KiB`;
  return `${(value / (1024 * 1024)).toFixed(1)} MiB`;
}

function yesNo(value: boolean): string {
  return value ? "yes" : "no";
}

const ENV_STATUS_LABEL: Record<DiagnosticsEnvStatus, string> = {
  set: "set",
  default: "using default",
  unset: "unset",
};

const ERROR_SOURCE_LABEL: Record<DiagnosticsErrorSourceId, string> = {
  scan_events: "Scan events (`level = error`)",
  scans: "Failed scans",
  runs: "Errored runs",
  process_log: "API process log",
};

export function renderDiagnosticsMarkdown(bundle: DiagnosticsBundle): string {
  const lines: string[] = [];

  lines.push("# Diagnostics bundle", "");
  lines.push(
    "_Generated by the app for a bug report. It carries **no environment variable values, no",
    "credentials and no user-typed names** — only versions, presence flags, counts and redacted",
    "error text. Nothing in here needs to be reviewed line by line before you paste it._",
    "",
  );
  lines.push(`- Bundle version: ${bundle.bundleVersion}`);
  lines.push(`- Generated at: ${escapeText(bundle.generatedAt)}`);
  lines.push("");

  // ── Versions ──────────────────────────────────────────────────────────────────────────────────
  lines.push("## Versions", "");
  lines.push("| Field | Value |", "| --- | --- |");
  lines.push(`| App | ${escapeMarkdownTable(bundle.versions.app)} |`);
  lines.push(`| Node | ${escapeMarkdownTable(bundle.versions.node)} |`);
  lines.push(
    `| Platform | ${escapeMarkdownTable(bundle.versions.platform)} / ${escapeMarkdownTable(bundle.versions.arch)} |`,
  );
  lines.push(`| Docker mode | ${yesNo(bundle.versions.dockerMode)} |`);
  lines.push("");

  // ── Environment ───────────────────────────────────────────────────────────────────────────────
  const setCount = bundle.environment.filter((entry) => entry.status === "set").length;
  const defaultCount = bundle.environment.filter((entry) => entry.status === "default").length;
  const unsetCount = bundle.environment.filter((entry) => entry.status === "unset").length;

  lines.push("## Environment", "");
  lines.push(
    "_Presence only. The app iterates a hard-coded list of the variables it recognises and records",
    "whether each is there — **no value is read**, not truncated, not hashed, not fingerprinted._",
    "",
  );
  lines.push(
    `${count(bundle.environment.length)} recognised variables — ${count(setCount)} set · ` +
      `${count(defaultCount)} using a built-in default · ${count(unsetCount)} unset.`,
    "",
  );
  lines.push("| Variable | Status |", "| --- | --- |");
  for (const entry of bundle.environment) {
    lines.push(`| \`${escapeMarkdownTable(entry.name)}\` | ${ENV_STATUS_LABEL[entry.status]} |`);
  }
  lines.push("");

  // ── Database ──────────────────────────────────────────────────────────────────────────────────
  lines.push("## Database", "");
  lines.push("| Field | Value |", "| --- | --- |");
  lines.push(`| Schema version on disk (\`user_version\`) | ${count(bundle.database.userVersion)} |`);
  lines.push(
    `| Latest version this build knows | ${count(bundle.database.latestKnownVersion)} |`,
  );
  lines.push(
    `| Up to date | ${bundle.database.upToDate ? "yes" : "**no — this install is mid-upgrade**"} |`,
  );
  lines.push(`| Database file | ${bytes(bundle.database.fileBytes)} |`);
  lines.push(`| Write-ahead log | ${bytes(bundle.database.walBytes)} |`);
  lines.push("");

  if (bundle.database.tables.length === 0) {
    lines.push("_No tables could be enumerated._", "");
  } else {
    lines.push("### Row counts", "");
    lines.push(
      "_Counts only. No row content, no names, no commands — a table's size is a shape, its",
      "contents are the operator's data._",
      "",
    );
    lines.push("| Table | Rows |", "| --- | ---: |");
    for (const table of bundle.database.tables) {
      lines.push(
        `| \`${escapeMarkdownTable(table.name)}\` | ${table.rows === null ? "not counted" : count(table.rows)} |`,
      );
    }
    lines.push("");
  }

  // ── Recent errors ─────────────────────────────────────────────────────────────────────────────
  lines.push("## Recent errors", "");
  lines.push(
    `_Every message below is passed through the app's shared redactor: credential-shaped runs are`,
    `masked, invisible characters are made visible, and each entry is capped at`,
    `${count(DIAGNOSTICS_ERROR_MAX_CHARS)} characters. At most`,
    `${count(DIAGNOSTICS_ERROR_ENTRY_LIMIT)} entries are listed._`,
    "",
  );

  lines.push("### Sources", "");
  lines.push("| Source | State |", "| --- | --- |");
  for (const source of bundle.errors.sources) {
    const state =
      source.status === "captured"
        ? `captured — ${count(source.matched)} recorded`
        : `**NOT CAPTURED** — ${escapeMarkdownTable(escapeText(source.reason))}`;
    lines.push(`| ${ERROR_SOURCE_LABEL[source.id]} | ${state} |`);
  }
  lines.push("");

  if (bundle.errors.entries.length === 0) {
    // Deliberately worded so it cannot be read as "this install has no errors": the sources table
    // above is where a NOT CAPTURED blind spot is declared, and this line points back at it.
    lines.push(
      "_No error rows were found in the captured sources listed above. Sources marked NOT CAPTURED",
      "were not searched at all._",
      "",
    );
  } else {
    lines.push("### Entries", "");
    if (bundle.errors.truncated) {
      lines.push(
        `_Truncated to the newest ${count(DIAGNOSTICS_ERROR_ENTRY_LIMIT)}; the source counts above are complete._`,
        "",
      );
    }
    lines.push("| When | Source | Message |", "| --- | --- | --- |");
    for (const entry of bundle.errors.entries) {
      const message = `${escapeMarkdownTable(escapeText(entry.message))}${entry.truncated ? " _(truncated)_" : ""}`;
      lines.push(
        `| ${escapeMarkdownTable(entry.at)} | ${ERROR_SOURCE_LABEL[entry.source]} | ${message} |`,
      );
    }
    lines.push("");
  }

  // ── Feature state ─────────────────────────────────────────────────────────────────────────────
  lines.push("## Feature state", "");
  lines.push("| Feature | Enabled |", "| --- | --- |");
  for (const flag of bundle.features.flags) {
    lines.push(`| \`${escapeMarkdownTable(flag.id)}\` | ${yesNo(flag.enabled)} |`);
  }
  lines.push("");

  lines.push("### Provider credentials", "");
  lines.push(
    "_A boolean per provider **kind**. No credential id, no operator label, no key material._",
    "",
  );
  lines.push("| Provider kind | Configured |", "| --- | --- |");
  for (const provider of bundle.features.providerKinds) {
    lines.push(
      `| \`${escapeMarkdownTable(provider.kind)}\` | ${yesNo(provider.configured)} |`,
    );
  }
  lines.push("");

  return `${lines.join("\n").trimEnd()}\n`;
}
