// The reference data pack contract (RM-38). Both ends read this: the API loads and verifies a pack
// against it, the web surfaces the resolved version, and the pack build stamps a manifest that
// satisfies it.
//
// HARD CONSTRAINT — this module imports `zod` and NOTHING else. No `node:fs`, no `node:crypto`, no
// network. It is a pure description of the contract plus pure helpers over already-computed values;
// reading bytes and hashing them is the API side's job (see `verifyManifestDigests` below, which
// takes digests as INPUT). `apps/api/test/data-pack.test.ts` scans this file's own source and fails
// on any other import specifier.

import { z } from "zod";

// --- Versioning ---------------------------------------------------------------------------------

/**
 * The pack layout/semantics version this build of the app writes and understands. An integer, not a
 * semver: it changes only when the SHAPE of a pack changes, never when its VALUES do (that is
 * `packVersion`). A pack whose `schemaVersion` is outside
 * [DATA_PACK_MIN_SUPPORTED_SCHEMA_VERSION, DATA_PACK_SCHEMA_VERSION] is refused whole (D-DP5).
 */
export const DATA_PACK_SCHEMA_VERSION = 1;

/** The oldest pack layout this build still accepts. */
export const DATA_PACK_MIN_SUPPORTED_SCHEMA_VERSION = 1;

/** True when this build can load a pack declaring `schemaVersion`. */
export function isSupportedDataPackSchemaVersion(schemaVersion: number): boolean {
  return (
    Number.isInteger(schemaVersion) &&
    schemaVersion >= DATA_PACK_MIN_SUPPORTED_SCHEMA_VERSION &&
    schemaVersion <= DATA_PACK_SCHEMA_VERSION
  );
}

// --- Pack layout (RM-38 WP 1.2) -----------------------------------------------------------------

/** The manifest's filename at the pack root. It is never listed in its own `files`. */
export const DATA_PACK_MANIFEST_FILENAME = "manifest.json";

/**
 * The directories whose `*.json` files ARE the pack, in manifest order. Everything else at the pack
 * root — `build/`, `package.json`, `tsconfig.json`, `relocation-ledger.json` — is repository
 * scaffolding, not pack content, and is neither digested nor shipped.
 *
 * `data-pack/build/manifest.ts` declares the same list as `PACK_CONTENT_DIRS` and deliberately does
 * NOT import it, so the pack build never needs `packages/shared` to be built first;
 * `apps/api/test/data-pack.test.ts` holds the two equal. Same pattern as
 * `PACK_SCHEMA_VERSION` / `DATA_PACK_SCHEMA_VERSION`.
 */
export const DATA_PACK_CONTENT_DIRS = [
  "compatibility",
  "generated",
  "limits",
  "models/open-weight",
  "models/saas",
  "schema",
] as const;

/**
 * Which schema (a pack-root-relative path) each pack file is validated against, or `null` for a
 * file that has no JSON Schema of its own.
 *
 * `generated/all-models.json` is deliberately `null`: it is a DERIVED artifact of the per-provider
 * model files, which each validate against `model-entry.schema.json`, and the loader checks it
 * structurally instead. `schema/*.json` are schemas, not instances — validating a schema against
 * itself proves nothing.
 */
export function dataPackSchemaFor(relPath: string): string | null {
  if (relPath.startsWith("models/")) return "schema/model-entry.schema.json";
  if (relPath === "limits/cross-cutting.json") return "schema/cross-cutting.schema.json";
  if (relPath === "compatibility/test-catalog.json") return "schema/test-catalog.schema.json";
  return null;
}

// --- Manifest -----------------------------------------------------------------------------------

/** One shipped pack file, addressed relative to the pack root with POSIX separators. */
export const DataPackManifestFileSchema = z
  .object({
    /** Pack-root-relative POSIX path, e.g. `models/saas/anthropic.json`. */
    path: z.string().min(1),
    /** Lowercase hex SHA-256 of the file's bytes. */
    sha256: z.string().regex(/^[0-9a-f]{64}$/),
    /** Byte length of the file on disk. */
    bytes: z.number().int().nonnegative(),
  })
  .strict();

export type DataPackManifestFile = z.infer<typeof DataPackManifestFileSchema>;

/**
 * `manifest.json` at the pack root. Generated by the pack build, never hand-edited; `files` covers
 * every shipped pack file EXCEPT the manifest itself (a manifest cannot digest itself).
 */
export const DataPackManifestSchema = z
  .object({
    /** Semver core, e.g. `1.0.0`. Ordered by `comparePackVersions`; a pack may not go backwards. */
    packVersion: z.string().regex(/^\d+\.\d+\.\d+$/),
    /** Pack LAYOUT version — see `DATA_PACK_SCHEMA_VERSION`. */
    schemaVersion: z.number().int().positive(),
    /** ISO date (YYYY-MM-DD) the newest fact in the pack was current as of. */
    asOf: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    /** Repo-relative path of the generator that wrote this manifest. */
    generator: z.string().min(1),
    files: z.array(DataPackManifestFileSchema).min(1),
  })
  .strict();

export type DataPackManifest = z.infer<typeof DataPackManifestSchema>;

// --- Refusals (D-DP5) ---------------------------------------------------------------------------

/**
 * The five ways a pack is refused. A pack is applied whole or not at all — there is no partial
 * trust and no per-file merge (D-DP2/D-DP5). Frozen tuple so the set is enumerable at runtime.
 */
export const DATA_PACK_REFUSAL_REASONS = [
  /** `schemaVersion` is missing, unparseable, or outside this build's supported range. */
  "unsupported_schema_version",
  /** A file's SHA-256 disagrees with the manifest, or the file set does not match it. */
  "digest_mismatch",
  /** A pack file failed its JSON Schema (or the manifest failed its own shape). */
  "schema_violation",
  /** `packVersion` is not greater than the pack currently in force. */
  "version_regression",
  /** The security rule-id ledger is not append-only against the bundled ledger (D-DP6). */
  "rule_ledger_not_append_only",
] as const;

export type DataPackRefusalReason = (typeof DATA_PACK_REFUSAL_REASONS)[number];

/** A refusal is a VALUE, never a throw — boot may not fail on data (D-DP4). */
export type DataPackRefusal = {
  reason: DataPackRefusalReason;
  /** One human sentence naming what was wrong, safe to log and to show in Settings. */
  detail: string;
  /** Pack-root-relative paths implicated, when the refusal is about specific files. */
  paths?: string[];
};

export const DataPackRefusalSchema = z
  .object({
    reason: z.enum(DATA_PACK_REFUSAL_REASONS),
    detail: z.string().min(1),
    paths: z.array(z.string()).optional(),
  })
  .strict();

// --- Pure helpers -------------------------------------------------------------------------------

/** A digest computed elsewhere (by `node:crypto` on the API side) for one pack-root-relative path. */
export type ComputedFileDigest = { sha256: string; bytes: number };

export type ManifestDigestVerification =
  | { ok: true }
  | { ok: false; refusal: DataPackRefusal & { reason: "digest_mismatch" } };

/**
 * Compare a manifest's `files` against digests computed from disk. PURE — it hashes nothing; the
 * caller supplies `computed`, keyed by the same pack-root-relative POSIX path.
 *
 * Fails on three distinct conditions, all of them `digest_mismatch`, because from a trust point of
 * view they are the same event — the bytes on disk are not the bytes the manifest describes:
 *   - a manifest entry with no file (missing),
 *   - a file present that the manifest does not list (unlisted — otherwise a pack could smuggle in
 *     an unverified file),
 *   - a digest or byte length that disagrees.
 */
export function verifyManifestDigests(
  files: readonly DataPackManifestFile[],
  computed: ReadonlyMap<string, ComputedFileDigest>,
): ManifestDigestVerification {
  const missing: string[] = [];
  const mismatched: string[] = [];
  const listed = new Set<string>();

  for (const entry of files) {
    listed.add(entry.path);
    const actual = computed.get(entry.path);
    if (!actual) {
      missing.push(entry.path);
      continue;
    }
    if (actual.sha256 !== entry.sha256 || actual.bytes !== entry.bytes) {
      mismatched.push(entry.path);
    }
  }

  const unlisted: string[] = [];
  for (const path of computed.keys()) {
    if (!listed.has(path)) unlisted.push(path);
  }

  if (missing.length === 0 && mismatched.length === 0 && unlisted.length === 0) return { ok: true };

  const parts: string[] = [];
  if (mismatched.length > 0) parts.push(`${mismatched.length} file(s) do not match their digest`);
  if (missing.length > 0) parts.push(`${missing.length} manifest file(s) are missing from the pack`);
  if (unlisted.length > 0) parts.push(`${unlisted.length} pack file(s) are not listed in the manifest`);

  return {
    ok: false,
    refusal: {
      reason: "digest_mismatch",
      detail: `Pack contents disagree with manifest.json: ${parts.join("; ")}.`,
      paths: [...mismatched, ...missing, ...unlisted].sort(),
    },
  };
}

const SEMVER_CORE = /^(\d+)\.(\d+)\.(\d+)$/;

/** True when `value` is a semver core (`MAJOR.MINOR.PATCH`, no prerelease, no build metadata). */
export function isValidPackVersion(value: string): boolean {
  return SEMVER_CORE.test(value);
}

/**
 * Order two pack versions. Returns `-1` when `a` precedes `b`, `0` when equal, `1` when `a` follows
 * `b`, and **`null` when either side is not a valid pack version** — an unorderable version must
 * refuse the pack (D-DP5 `version_regression`), never silently compare as equal.
 */
export function comparePackVersions(a: string, b: string): -1 | 0 | 1 | null {
  const ma = SEMVER_CORE.exec(a);
  const mb = SEMVER_CORE.exec(b);
  if (!ma || !mb) return null;
  for (let i = 1; i <= 3; i++) {
    const na = Number(ma[i]);
    const nb = Number(mb[i]);
    if (na < nb) return -1;
    if (na > nb) return 1;
  }
  return 0;
}
