import {
  Activity,
  AlarmClock,
  Album,
  Anchor,
  Aperture,
  AreaChart,
  Atom,
  Award,
  BarChart3,
  Beaker,
  Bell,
  Binary,
  Blocks,
  Bolt,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Calculator,
  Calendar,
  ChartPie,
  CircuitBoard,
  Cloud,
  Code,
  Cog,
  Compass,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Feather,
  FileSearch,
  FileText,
  FlaskConical,
  Flame,
  Folder,
  GaugeCircle,
  Gem,
  GitBranch,
  Github,
  Globe,
  GraduationCap,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Home,
  Image as ImageIcon,
  Inbox,
  Key,
  Landmark,
  Languages,
  Layers,
  Leaf,
  LibraryBig,
  LifeBuoy,
  LineChart,
  Link,
  ListChecks,
  Lock,
  type LucideIcon,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Megaphone,
  MessageSquare,
  Mic,
  Microscope,
  Moon,
  Network,
  Newspaper,
  Package,
  Palette,
  PenTool,
  Phone,
  PieChart,
  Pin,
  Plane,
  Plug,
  Puzzle,
  Radar,
  Radio,
  Rocket,
  Route,
  Ruler,
  ScanLine,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Signal,
  Sparkles,
  Star,
  Sun,
  Table2,
  Tag,
  Target,
  Telescope,
  Terminal,
  ThumbsUp,
  Trophy,
  Truck,
  Users,
  Wallet,
  Wand2,
  Waypoints,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Assistant Hub — the curated glyph library the {@link IconPicker} pans over (owner request: "real
 * icons for my agents", ≈120 icons). Explicit named imports keep the bundle tree-shakeable (an
 * `import * as` would pull all ~1600 lucide icons). Each entry's `name` is the stored value after the
 * `lucide:` prefix (see `parseHubIcon`/`hubLucideIconValue` in `@mcp-token-footprint/shared`).
 *
 * Names are kebab-cased to match lucide's own icon-name convention, so a legacy free-text `icon`
 * value that happens to be a real lucide name (e.g. `"search"`, `"database"`) resolves through
 * {@link HUB_ICON_BY_NAME} with no migration.
 */
export type HubIconEntry = { name: string; Icon: LucideIcon };
export type HubIconGroup = { label: string; icons: HubIconEntry[] };

export const HUB_ICON_GROUPS: HubIconGroup[] = [
  {
    label: "People & agents",
    icons: [
      { name: "bot", Icon: Bot },
      { name: "brain", Icon: Brain },
      { name: "users", Icon: Users },
      { name: "sparkles", Icon: Sparkles },
      { name: "wand-2", Icon: Wand2 },
      { name: "graduation-cap", Icon: GraduationCap },
      { name: "briefcase", Icon: Briefcase },
      { name: "award", Icon: Award },
      { name: "trophy", Icon: Trophy },
      { name: "heart", Icon: Heart },
      { name: "thumbs-up", Icon: ThumbsUp },
      { name: "star", Icon: Star },
    ],
  },
  {
    label: "Data & analytics",
    icons: [
      { name: "database", Icon: Database },
      { name: "bar-chart-3", Icon: BarChart3 },
      { name: "line-chart", Icon: LineChart },
      { name: "pie-chart", Icon: PieChart },
      { name: "chart-pie", Icon: ChartPie },
      { name: "area-chart", Icon: AreaChart },
      { name: "activity", Icon: Activity },
      { name: "table-2", Icon: Table2 },
      { name: "calculator", Icon: Calculator },
      { name: "gauge-circle", Icon: GaugeCircle },
      { name: "radar", Icon: Radar },
      { name: "scan-line", Icon: ScanLine },
      { name: "binary", Icon: Binary },
      { name: "hash", Icon: Hash },
      { name: "ruler", Icon: Ruler },
      { name: "scale", Icon: Scale },
    ],
  },
  {
    label: "Dev & systems",
    icons: [
      { name: "code", Icon: Code },
      { name: "terminal", Icon: Terminal },
      { name: "cpu", Icon: Cpu },
      { name: "server", Icon: Server },
      { name: "hard-drive", Icon: HardDrive },
      { name: "circuit-board", Icon: CircuitBoard },
      { name: "git-branch", Icon: GitBranch },
      { name: "github", Icon: Github },
      { name: "network", Icon: Network },
      { name: "workflow", Icon: Workflow },
      { name: "waypoints", Icon: Waypoints },
      { name: "blocks", Icon: Blocks },
      { name: "box", Icon: Box },
      { name: "layers", Icon: Layers },
      { name: "puzzle", Icon: Puzzle },
      { name: "plug", Icon: Plug },
      { name: "cog", Icon: Cog },
      { name: "settings", Icon: Settings },
      { name: "wrench", Icon: Wrench },
      { name: "bug", Icon: Bug },
      { name: "bolt", Icon: Bolt },
      { name: "zap", Icon: Zap },
    ],
  },
  {
    label: "Research & science",
    icons: [
      { name: "microscope", Icon: Microscope },
      { name: "flask-conical", Icon: FlaskConical },
      { name: "beaker", Icon: Beaker },
      { name: "atom", Icon: Atom },
      { name: "telescope", Icon: Telescope },
      { name: "search", Icon: Search },
      { name: "file-search", Icon: FileSearch },
      { name: "book-open", Icon: BookOpen },
      { name: "library-big", Icon: LibraryBig },
      { name: "newspaper", Icon: Newspaper },
      { name: "compass", Icon: Compass },
      { name: "aperture", Icon: Aperture },
    ],
  },
  {
    label: "Comms & content",
    icons: [
      { name: "message-square", Icon: MessageSquare },
      { name: "mail", Icon: Mail },
      { name: "send", Icon: Send },
      { name: "inbox", Icon: Inbox },
      { name: "megaphone", Icon: Megaphone },
      { name: "bell", Icon: Bell },
      { name: "phone", Icon: Phone },
      { name: "mic", Icon: Mic },
      { name: "headphones", Icon: Headphones },
      { name: "radio", Icon: Radio },
      { name: "signal", Icon: Signal },
      { name: "share-2", Icon: Share2 },
      { name: "languages", Icon: Languages },
      { name: "pen-tool", Icon: PenTool },
      { name: "feather", Icon: Feather },
      { name: "file-text", Icon: FileText },
      { name: "image", Icon: ImageIcon },
      { name: "palette", Icon: Palette },
    ],
  },
  {
    label: "Business & ops",
    icons: [
      { name: "target", Icon: Target },
      { name: "list-checks", Icon: ListChecks },
      { name: "dollar-sign", Icon: DollarSign },
      { name: "credit-card", Icon: CreditCard },
      { name: "wallet", Icon: Wallet },
      { name: "shopping-cart", Icon: ShoppingCart },
      { name: "landmark", Icon: Landmark },
      { name: "building-2", Icon: Building2 },
      { name: "package", Icon: Package },
      { name: "truck", Icon: Truck },
      { name: "tag", Icon: Tag },
      { name: "calendar", Icon: Calendar },
      { name: "alarm-clock", Icon: AlarmClock },
      { name: "life-buoy", Icon: LifeBuoy },
    ],
  },
  {
    label: "Security & keys",
    icons: [
      { name: "shield", Icon: Shield },
      { name: "shield-check", Icon: ShieldCheck },
      { name: "lock", Icon: Lock },
      { name: "key", Icon: Key },
      { name: "magnet", Icon: Magnet },
    ],
  },
  {
    label: "World & shapes",
    icons: [
      { name: "globe", Icon: Globe },
      { name: "map", Icon: MapIcon },
      { name: "map-pin", Icon: MapPin },
      { name: "pin", Icon: Pin },
      { name: "route", Icon: Route },
      { name: "link", Icon: Link },
      { name: "anchor", Icon: Anchor },
      { name: "plane", Icon: Plane },
      { name: "rocket", Icon: Rocket },
      { name: "cloud", Icon: Cloud },
      { name: "sun", Icon: Sun },
      { name: "moon", Icon: Moon },
      { name: "flame", Icon: Flame },
      { name: "leaf", Icon: Leaf },
      { name: "gem", Icon: Gem },
      { name: "hexagon", Icon: Hexagon },
      { name: "album", Icon: Album },
      { name: "folder", Icon: Folder },
      { name: "home", Icon: Home },
    ],
  },
];

/** Flat name → component lookup for the renderer ({@link RoleAvatar}). Undefined for an unknown name. */
export const HUB_ICON_BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  HUB_ICON_GROUPS.flatMap((group) => group.icons.map((entry) => [entry.name, entry.Icon])),
);
