/**
 * Agent — exemplar entity component for the illustration design system.
 *
 * This file demonstrates, in one place, what WP 0.2/0.3 will split into
 * `packages/illustrations/src/{primitives,entities,registry}`:
 *
 *   - true-iso math + the face-map transform      (D-IL15, research §3.1)
 *   - three-face light model via --illus-* tokens (D-IL5/D-IL15, research §3.3–3.4)
 *   - one accent moment (the antenna LED)         (D-IL6)
 *   - the closed state set                        (D-IL8)
 *   - named ports declared in registry metadata   (D-IL7/D-IL9)
 *   - fixed paint order: shadow → ghost → structure → detail → accent (D-IL16)
 *
 * NO color literals appear anywhere — every fill/stroke is a --illus-* variable,
 * bound to the live theme by tokens.css. Rendered previews (both themes):
 * agent-bright.png / agent-dark.png, generated by build-agent-example.py.
 */

import type { ReactNode } from "react";

/* ---------------------------------------------------------------- *
 * iso-math (→ packages/illustrations/src/primitives/iso-math.ts)
 * ---------------------------------------------------------------- */

/** 1 iso unit = 16 px (D-IL2). Footprints quantized: S 4×4 · M 6×6 · L 8×8. */
export const UNIT = 16;
const KX = Math.cos(Math.PI / 6) * UNIT; // 13.856 — true iso, not 2:1
const KY = Math.sin(Math.PI / 6) * UNIT; // 8

/** Project a world point (iso units, z up) to screen px. */
export function project(x: number, y: number, z: number): [number, number] {
  return [(x - y) * KX, (x + y) * KY - z * UNIT];
}

/**
 * Face-map transform: mounts flat, screen-space art onto the RIGHT (+x) face
 * of a solid (local x runs along the face as viewed, local y runs down).
 * top/left variants differ only in the fixed matrix (research §3.1).
 */
export function faceMatrixRight(originX: number, originY: number): string {
  return `matrix(0.866,-0.5,0,1,${originX},${originY})`;
}

/** Same, for the LEFT (+y) face — the upstream gaze side in a L→R scene. */
export function faceMatrixLeft(originX: number, originY: number): string {
  return `matrix(0.866,0.5,0,1,${originX},${originY})`;
}

type Pt = [number, number];
const pts = (ps: Pt[]) => ps.map(([a, b]) => `${a.toFixed(1)},${b.toFixed(1)}`).join(" ");

/* ---------------------------------------------------------------- *
 * IsoBox primitive (→ src/primitives/IsoHousing.tsx / IsoPlatform.tsx)
 * Three visible faces, painted back-to-front, lit by the fixed rule:
 * top = --illus-face-top · left(+y) = --illus-face-left · right(+x) = --illus-face-right
 * ---------------------------------------------------------------- */

function IsoBox(props: {
  cx: number; cy: number; w: number; d: number; z0: number; h: number; sw?: number;
}) {
  const { cx, cy, w, d, z0, h, sw = 1.6 } = props;
  const zt = z0 + h;
  const A = project(cx - w / 2, cy - d / 2, zt);
  const B = project(cx + w / 2, cy - d / 2, zt);
  const C = project(cx + w / 2, cy + d / 2, zt);
  const D = project(cx - w / 2, cy + d / 2, zt);
  const Bb = project(cx + w / 2, cy - d / 2, z0);
  const Cb = project(cx + w / 2, cy + d / 2, z0);
  const Db = project(cx - w / 2, cy + d / 2, z0);
  const stroke = { stroke: "var(--illus-ink)", strokeWidth: sw, strokeLinejoin: "round" as const };
  return (
    <g>
      <polygon points={pts([D, C, Cb, Db])} style={{ fill: "var(--illus-face-left)" }} {...stroke} />
      <polygon points={pts([B, C, Cb, Bb])} style={{ fill: "var(--illus-face-right)" }} {...stroke} />
      <polygon points={pts([A, B, C, D])} style={{ fill: "var(--illus-face-top)" }} {...stroke} />
    </g>
  );
}

/* ---------------------------------------------------------------- *
 * Shared entity contract (→ src/entities/types.ts)
 * ---------------------------------------------------------------- */

export type EntityState = "idle" | "active" | "highlight" | "dimmed" | "error";
export type EntitySize = "s" | "m" | "l";
/** Gaze rule (D-IL17): faces meet the flow. Default = upstream (toward incoming). */
export type EntityFacing = "upstream" | "downstream";

export interface EntityProps {
  size?: EntitySize;          // quantized footprint (this exemplar implements "m")
  state?: EntityState;        // closed set (D-IL8)
  facing?: EntityFacing;      // gaze side; scene layout may set it per node (D-IL17)
  label?: string;             // screen-aligned, never skewed onto a face
  showPorts?: boolean;        // dev/gallery overlay of the registry port map
}

/* ---------------------------------------------------------------- *
 * Registry entry (→ src/registry.ts) — the machine-readable half.
 * Consumed by the gallery, the scene validator, and the assistant tools.
 * Ports are declared here (world-space anchors), NOT measured from the DOM.
 * ---------------------------------------------------------------- */

export const agentMeta = {
  id: "agent",
  title: "Agent / LLM",
  entity: "runs" as const,           // the domain concept it most often depicts
  tier: 1 as const,
  keywords: ["agent", "llm", "model", "robot", "primary llm", "assistant"],
  variants: ["upstream", "downstream"],   // gaze sides (D-IL17)
  states: ["idle", "active", "highlight", "dimmed", "error"] as EntityState[],
  sizes: ["m"] as EntitySize[],
  since: "0.1.0",
  description:
    "An LLM agent: robot housing on a two-tier isometric platform; antenna LED is its status accent.",
  ports: {
    top: { at: project(0, 0, 5.35) },          // loop/annotation attachments
    bottom: { at: project(2.8, 2.8, 0) },       // grounding / storage
    "context-in": { at: project(-2.8, 2.8, 0.35) },  // skills, MCP tools, prompts in
    "result-out": { at: project(2.8, -2.8, 0.35) },  // answers, tool calls out
  },
};

/* ---------------------------------------------------------------- *
 * The component (→ src/entities/Agent.tsx)
 * ---------------------------------------------------------------- */

export default function Agent({ state = "idle", facing = "upstream", label, showPorts = false }: EntityProps) {
  const [sx, sy] = project(0.25, 0.25, 0);
  const [ax, ay] = project(0, 0, 4.58);      // antenna base (head top)
  const [tx, ty] = project(0, 0, 5.35);      // antenna tip — THE accent moment
  // gaze side (D-IL17): upstream → LEFT (+y) face; downstream → RIGHT (+x) face
  const up = facing === "upstream";
  const [hfx, hfy] = up ? project(-1.1, 1.1, 4.58) : project(1.1, 1.1, 4.58);
  const [bfx, bfy] = up ? project(-1.45, 1.45, 2.9) : project(1.45, 1.45, 2.9);
  const faceMatrix = up ? faceMatrixLeft : faceMatrixRight;
  const ghost = ([-7, -5] as Pt) && ([[-2.8, -2.8], [2.8, -2.8], [2.8, 2.8], [-2.8, 2.8]] as Pt[])
    .map(([x, y]) => { const [px, py] = project(x, y, 0.7); return [px - 7, py - 5] as Pt; });
  const tip = state === "error" ? "var(--illus-error)" : "var(--illus-accent)";
  const eye = state === "error" ? "var(--illus-error)" : "var(--illus-ink)";

  return (
    // viewBox centers the component; scenes translate the group via the layout engine
    <svg viewBox="-116 -190 232 224" role="img" aria-labelledby="agent-t agent-d" width={232}>
      <title id="agent-t">{label ?? agentMeta.title}</title>
      <desc id="agent-d">{agentMeta.description}</desc>

      <g opacity={state === "dimmed" ? 0.32 : 1}>
        {/* shadows layer */}
        <ellipse cx={sx} cy={sy} rx={56} ry={27} style={{ fill: "var(--illus-ink)" }} fillOpacity={0.07} />
        {state === "highlight" && (
          <ellipse cx={sx} cy={sy + 6} rx={78} ry={38} style={{ fill: "var(--illus-accent)" }} fillOpacity={0.28} />
        )}

        {/* construction ghost — the drafting layer, not wobble (research §3.2) */}
        <polygon points={pts(ghost)} fill="none" strokeDasharray="4 4" strokeWidth={1}
          style={{ stroke: "var(--illus-guide)" }} />

        {/* structure layer, back-to-front */}
        <IsoBox cx={0} cy={0} w={5.6} d={5.6} z0={0} h={0.7} sw={1.8} />
        <IsoBox cx={0} cy={0} w={4.2} d={4.2} z0={0.7} h={0.5} />
        <IsoBox cx={0} cy={0} w={2.9} d={2.9} z0={1.2} h={1.8} sw={1.8} />
        <IsoBox cx={0} cy={0} w={0.9} d={0.9} z0={3.0} h={0.18} sw={1.2} />
        <IsoBox cx={0} cy={0} w={2.2} d={2.2} z0={3.18} h={1.4} sw={1.8} />

        {/* detail layer — flat art mounted with the face-map transform (D-IL15) */}
        <g transform={faceMatrix(hfx, hfy)}>
          <rect x={4} y={5.5} width={27.2} height={13} rx={3} strokeWidth={1.2}
            style={{ fill: "var(--illus-surface-sunken)", stroke: "var(--illus-ink)" }} />
          <circle cx={12} cy={12} r={2.6} style={{ fill: eye }} />
          <circle cx={23.2} cy={12} r={2.6} style={{ fill: eye }} />
        </g>
        <g transform={faceMatrix(bfx, bfy)} strokeWidth={2} strokeLinecap="round"
          style={{ stroke: "var(--illus-ink-muted)" }}>
          <line x1={7} y1={8} x2={27} y2={8} />
          <line x1={7} y1={14} x2={20} y2={14} />
        </g>

        {/* antenna — the single accent moment (D-IL6) */}
        <line x1={ax} y1={ay} x2={tx} y2={ty} strokeWidth={1.8} style={{ stroke: "var(--illus-ink)" }} />
        <circle cx={tx} cy={ty} r={3.6} style={{ fill: tip }} />
        {state === "active" && (
          <circle cx={tx} cy={ty} r={8} fill="none" strokeWidth={1.5} opacity={0.55}
            style={{ stroke: "var(--illus-accent)" }} />
        )}
        {state === "error" && (
          <circle cx={tx} cy={ty} r={8} fill="none" strokeWidth={1.5} strokeDasharray="3 3"
            opacity={0.7} style={{ stroke: "var(--illus-error)" }} />
        )}
      </g>

      {/* dev/gallery port overlay, from registry metadata (D-IL7) */}
      {showPorts &&
        Object.entries(agentMeta.ports).map(([name, p]) => (
          <g key={name}>
            <circle cx={p.at[0]} cy={p.at[1]} r={4} stroke="var(--illus-paper)" strokeWidth={1.4}
              style={{ fill: "var(--illus-accent)" }} />
            <text x={p.at[0]} y={p.at[1] + 16} fontSize={10.5} textAnchor="middle"
              style={{ fill: "var(--illus-ink)", fontFamily: "var(--font-sans, Inter, sans-serif)" }}>
              {name}
            </text>
          </g>
        ))}

      {/* label slot — screen-aligned (research §3.1) */}
      {label && (
        <text x={0} y={28} fontSize={13} fontWeight={600} textAnchor="middle"
          style={{ fill: "var(--illus-ink)", fontFamily: "var(--font-sans, Inter, sans-serif)" }}>
          {label}
        </text>
      )}
    </svg>
  );
}

/* ---------------------------------------------------------------- *
 * tokens.css excerpt (→ packages/illustrations/src/tokens.css)
 * The ONLY place --illus-* meets @elabs-ai/components-tokens (D-IL5):
 *
 *   :root, [data-theme] {
 *     --illus-paper:          var(--background);
 *     --illus-grid:           var(--grid-line, var(--canvas-grid));
 *     --illus-ink:            var(--foreground);
 *     --illus-ink-muted:      var(--muted-foreground);
 *     --illus-guide:          var(--rule, var(--border));
 *     --illus-face-top:       var(--card);
 *     --illus-face-left:      color-mix(in oklch, var(--card), var(--foreground) 16%);
 *     --illus-face-right:     color-mix(in oklch, var(--card), var(--foreground) 34%);
 *     --illus-surface-sunken: var(--surface-muted);
 *     --illus-accent:         var(--primary);
 *     --illus-accent-contrast:var(--primary-foreground);
 *     --illus-error:          var(--destructive);
 *   }
 * ---------------------------------------------------------------- */
